
[flyway]
locations = ["filesystem:migrations"]
 
[environments.default]
locations = ["filesystem:migrations"]

# Update the URL to connect to your MSSQL server

url = "${{ secrets.DB_BUILD_URL }}"
user = "${{ secrets.DB_BUILD_USERNAME }}" 
password = "${{ secrets.DB_BUILD_PASSWORD }}"
